---
version: '2.1'
services:
  xc-minio:
    # Dit is de minio image voor het aanleveren van xeno-canto bronnen
    image: minio/minio
    restart: unless-stopped
    command: server /export
    environment:
      # minimal 5 chars
      MINIO_ACCESS_KEY: ${XENOCANTO_S3_USER:-xenocanto}
      # minimal 8 chars
      MINIO_SECRET_KEY: ${XENOCANTO_S3_PASS:-xenocanto}
      MINIO_DOMAIN: s3.xenocanto.ppdb.naturalis.nl
    volumes:
    - "${MINIO_XENOCANTO_DATA_DIR:-./minio-xenocanto}:/export"
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    labels:
      - "traefik.backend=xc-minio"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "${MINIO_XC_URL:-traefik.frontend.rule=Host:s3.xenocanto.ppdb.naturalis.nl,multimedia.s3.xenocanto.ppdb.naturalis.nl,specimen.s3.xenocanto.ppdb.naturalis.nl,reports.s3.xenocanto.ppdb.naturalis.nl}"
  wrnnl-minio:
    # Dit is de minio image voor het aanleveren van waarneming bronnen
    image: minio/minio
    restart: unless-stopped
    command: server /export
    environment:
      # minimal 5 chars
      MINIO_ACCESS_KEY: ${WAARNEMING_S3_USER:-waarneming}
      # minimal 8 chars
      MINIO_SECRET_KEY: ${WAARNEMING_S3_PASS:-waarneming}
      MINIO_DOMAIN: s3.waarneming.ppdb.naturalis.nl
    volumes:
    - "${MINIO_WAARNEMING_DATA_DIR:-./minio-waarneming}:/export"
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    labels:
      - "traefik.backend=waarneming-minio"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "${MINIO_WRNNL_URL:-traefik.frontend.rule=Host:s3.waarneming.ppdb.naturalis.nl,multimedia.s3.waarneming.ppdb.naturalis.nl,specimen.s3.waarneming.ppdb.naturalis.nl,reports.s3.waarneming.ppdb.naturalis.nl}"
  naturalis-minio:
    # Dit is de minio image voor het aanleveren van naturalis bronnen
    image: minio/minio
    restart: unless-stopped
    command: server /export
    environment:
      # minimal 5 chars
      MINIO_ACCESS_KEY: ${NATURALIS_S3_USER:-naturalis}
      # minimal 8 chars
      MINIO_SECRET_KEY: ${NATURALIS_S3_PASS:-naturalis}
      MINIO_DOMAIN: s3.naturalis.ppdb.naturalis.nl
    volumes:
    - "${MINIO_NATURALIS_DATA_DIR:-./minio-naturalis}:/export"
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    labels:
      - "traefik.backend=naturalis-minio"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "${MINIO_NATURALIS_URL:-traefik.frontend.rule=Host:s3.naturalis.ppdb.naturalis.nl,multimedia.s3.naturalis.ppdb.naturalis.nl,specimen.s3.naturalis.ppdb.naturalis.nl,reports.s3.naturalis.ppdb.naturalis.nl}"
  traefik:
    # Traefik verzorgt het ssl certificate en de communicatie via de load balancer
    image: traefik:1.7.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.log:/var/log/traefik
      - "/etc/letsencrypt:/etc/letsencrypt"
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
  elasticsearch:
    # Dit is de elastic logging server
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      - "discovery.type=single-node"
    volumes:
      - "${ELASTICSEARCH_DATA:-./elasticsearch-data}:/usr/share/elasticsearch/data"
      - "${ELASTICSEARCH_BACKUP:-./elasticsearch-backup}:/backup"
    ports:
      - "127.0.0.1:9200:9200"
  grafana:
    # Dit is het grafana dashboard dat de logging van het hele proces kan weergeven
    image: grafana/grafana
    volumes:
      - "${GRAFANA_DATA:-./grafana-data}:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS:-secret}
    networks:
      - web
      - default
    labels:
      - "traefik.backend=ppdb-grafana"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:reports.ppdb.naturalis.nl}
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
  postgres:
    # Dit is de postgres database die wordt gebruikt door de percolator instance
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - "${PG_DATA:-./pgdata}:/var/lib/postgresql/data"
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d
      - "${SHARED_DATA:-./shared-data}:/shared-data" # python data share
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REPLICATION_USER=${REPLICATION_USER}
      - REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - default
  validator:
    # Dit is de validator instance van Maarten
    image: naturalis/nba-validator:v1.0
    volumes:
      - "${NBA_JSON_SCHEMAS:-./nba_json_schemas}:/schemas"
      - "${NBA_JSON_CONFIG:-./nba_validator_config}:/config"
      - "${VALIDATOR_DATA:-./data/validator}:/data"
      - "${SHARED_DATA:-./data/shared-data}:/shared-data"
    environment:
      repository: /data/datasets
      outdir: /data/output
      logserver: http://${LOGGING_HOST}:${LOGGING_PORT:-9200}/
      jobfolder: /shared-data/percolator/jobs/
      datafolder: /shared-data/percolator/incoming/
      outfile_lines: 0
      tmp_path: /data/temporary/
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - web
      - default
  percolator:
    # Dit is de percolator instance van Joep
    image: naturalis/nba-percolator:latest
    volumes:
      - "${SHARED_DATA:-./shared-data}:/shared-data"
      - "${MINIO_WAARNEMING_DATA_DIR:-./data}:/infuser-data"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}@${POSTGRES_PASSWORD}/${POSTGRES_DB}"
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${POSTGRES_HOST}
      PERCOLATOR_CONFIG: ${PERCOLATOR_CONFIG:-./config.yml}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      SLACK_ENABLED: ${SLACK_ENABLED:-0}
      LOGGING_HOST: ${LOGGING_HOST:-9200}
      LOGGING_PORT: ${LOGGING_PORT:-elasticsearch}
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - default
  nba-loader:
    # Dit is de infuser/importer van Tom
    image: naturalis/nba-loader:latest
    volumes:
      - /opt/ppdb/loader-config:/home/app/config
      - /data/shared-data/infuser:/data
    environment:
      NBA_HOST: ${NBA_HOST:-127.0.0.1}
      NBA_PORT: ${NBA_PORT:-9200}
      NBA_SCHEME: ${NBA_SCHEME:-http}
      LOGGING_HOST: ${LOGGING_HOST}
      LOGGING_PORT: ${LOGGING_PORT:-9200}
      LOGGING_SCHEME: ${LOGGING_SCHEME:-http}
      INFUSER_BATCHSIZE: ${INFUSER_BATCHSIZE:-500}
      INFUSER_JOBSPATH: ${INFUSER_JOBSPATH}
      INFUSER_INCOMINGPATH: ${INFUSER_INCOMINGPATH}
      INFUSER_ARCHIVEPATH: ${INFUSER_ARCHIVEPATH}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      SLACK_ENABLED: ${SLACK_ENABLED:-0}
    networks:
      - default
########
# Onderstaand is de dev omgeving gebruikt om tijdens een vroeg moment te experimenteren
#
# jupyter:
#   image: naturalis/ppdb:v0.0.1
#   volumes:
#     - "${SHARED_DATA:-./shared-data}:/shared-data"
#     - "${PYTHON_CODE:-./python-code}:/home/jovyan/src"
#     - "${NOTEBOOKS:-./notebooks}:/home/jovyan/notebooks"
#     - "${VALIDATOR_DATA:-./data}:/validator-data"
#   labels:
#     - "traefik.backend=ppdb-jupyter"
#     - "traefik.docker.network=web"
#     - "traefik.enable=true"
#     - "traefik.port=8888"
#     - ${JUPYTER_URL_CONFIG:-traefik.frontend.rule=Host:jupyter.ppdb.naturalis.nl}
#   environment:
#     DATABASE_URL: "postgres://${POSTGRES_USER}@${POSTGRES_PASSWORD}/${POSTGRES_DB}"
#     DATABASE_USER: ${POSTGRES_USER}
#     DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
#     DATABASE_DB: ${POSTGRES_DB}
#     DATABASE_HOST: ${POSTGRES_HOST}
#     PERCOLATOR_CONFIG: ${PERCOLATOR_CONFIG}
#   logging:
#     driver: "json-file"
#     options:
#       max-size: '10m'
#       max-file: '5'
#   networks:
#     - web
#     - default
#
#
#  gui:
#    image: naturalis/nba-json-validator-gui:latest
#    networks:
#      - default
#      - web
#    ports:
#      - 5678:80
#    logging:
#      driver: "json-file"
#      options:
#        max-size: '10m'
#        max-file: '5'
#    labels:
#      - "traefik.backend=validator-gui"
#      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "${MINIO_WRNNL_URL:-traefik.frontend.rule=Host:validator.ppdb.naturalis.nl}"

networks:
  web:
    external: true
